# Properties for com.titania.harp.workflow 
portalUrl=http://localhost:8080/doc-review
loginPage=/login
observerPage=/pages/process/yObserver.ftl
user=titaniaWFService@titaniasoftware.com
password=PaulTyson1
